name: Update Google Sheet

on:
  workflow_dispatch:      # ручной запуск из UI
  schedule:
    - cron: "0 3 * * *"

jobs:
  push-to-sheet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          pip install \
            gspread \
            oauth2client \
            gspread-dataframe \
            pandas \
            streamlit

      - name: Update Google Sheet
        run: python update_sheet.py
        env:
          GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          MAIN_SS_ID:          ${{ secrets.MAIN_SS_ID }}
          MAIN_SHEET:          ${{ secrets.MAIN_SHEET }}
          LEADS_SS_ID:         ${{ secrets.LEADS_SS_ID }}
          LEADS_SHEET:         ${{ secrets.LEADS_SHEET }}
