name: Update Google Sheet

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  push-to-sheet:
    runs-on: ubuntu-latest
    steps:                     # ← обязателен
      - uses: actions/checkout@v3

      - name: Install deps     # ← ровно два пробела от «steps:»
        run: |
          pip install \
            gspread \
            oauth2client \
            gspread-dataframe \
            pandas \
            streamlit

      - name: Update Google Sheet
        run: python update_sheet.py
        env:
          GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
